# version: '3.8'

# services:
#   app:
#     build: .
#     container_name: laravel_app
#     restart: always
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#     depends_on:
#       - db
#     networks:
#       - laravel

#   db:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_DATABASE: Hello
#       MYSQL_USER: root
#       MYSQL_PASSWORD: Vid@13579
#       MYSQL_ROOT_PASSWORD: Vid@13579
#     ports:
#       - "3306:3306"
#     networks:
#       - laravel
#     volumes:
#       - mysql_data:/var/lib/mysql

#   nginx:
#     image: nginx:latest
#     container_name: nginx_server
#     restart: always
#     ports:
#       - "8000:80"
#     volumes:
#       - .:/var/www
#       - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - laravel

# networks:
#   laravel:

# volumes:
#   mysql_data:
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: laravel
      MYSQL_USER: "root"
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8080:80"
  